# Generated by Django 5.0.2 on 2024-02-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0001_initial'),
        ('core', '0002_employee_email_employee_phone_numer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
