# Generated by Django 5.0.2 on 2024-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0002_event_rate_event_role_alter_event_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
