# Generated by Django 5.0.2 on 2024-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0004_event_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
