# Generated by Django 5.0.2 on 2024-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0005_remove_event_title_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
