# Generated by Django 5.0.2 on 2024-02-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_phone_numer_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
