# Generated by Django 5.0.2 on 2024-02-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_phone_numer_employee_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='location',
            new_name='name',
        ),
    ]
